### PR TITLE
appendicies: copybody suggested corrections

### PR DESCRIPTION
**Pull request by bahtou**

### CODE REVIEW

**Comment by bebraw** [comment]
@bahtou Thanks a lot for the PRs! I asked someone else to have a look too. It was a long day for me so I'll try to get these in tomorrow after work while doing some other fixes.

**Comment by bebraw** [comment]
@bahtou Also, let me know how to credit you. 👍

**Comment by bahtou** [comment]
@bebraw what do you mean by credit?

**Comment by bebraw** [comment]
Hi,

That's just for the book intro. I can use your GitHub nick or name as you
prefer.

**Comment by bahtou** [comment]
I see. You can use   Roberto Fuentes.
At your service :)

**Comment by bebraw** [comment]
Thanks a lot again. I'll publish a minor version with your tweaks shortly. 👍

**Pull request merged**
